const GET_CATEGORIES = 'GET_CATEGORIES';
const GET_ALL_MEALS = 'GET_ALL_MEALS';
const GET_BY_NAME = 'GET_BY_NAME';
const GET_BY_CATEGORY = 'GET_BY_CATEGORY';
const CHANGE_FILTER = 'CHANGE_FILTER';

export {
  GET_CATEGORIES, GET_ALL_MEALS, GET_BY_NAME, GET_BY_CATEGORY, CHANGE_FILTER,
};
